# Messages shown to the player under certain circumstances.
messages:
  join:
  permission:
  respawn:
  sticky:
  villager:

# When enabled this will allow players to trade books in Lore's library to villagers.
# Default: false
allow-villager-trades: false