name: @name@
version: @version@
description: @description@
author: @authors@
website: @url@

main: @mainClass@
load: POSTWORLD

commands:
  lore:
    description: Commands to manage Lore.
    usage: |
      /lore create [name]
      /lore give [player] [book]
      /lore join [book] [true|false]
      /lore list
      /lore remove [book]
      /lore respawn [book] [true|false]
      /lore sticky [book] [true|false]

permissions:
  lore.command.*:
    description: Combines all 'command' permissions under one wildcard.
    children:
      lore.command.create: true
      lore.command.give: true
      lore.command.join: true
      lore.command.list: true
      lore.command.remove: true
      lore.command.respawn: true
      lore.command.sticky: true
  lore.command.create:
    description: Allows the player to add a new book to Lore's book library.
    default: false
  lore.command.give:
    description: Allows the player to give any book to another player.
    default: false
  lore.command.join:
    description: Allows the player to set the flag for "join" on Lore books.
    default: false
  lore.command.remove:
    description: Allows the player to remove a book from Lore's book library.
    default: false
  lore.command.list:
    description: Displays a list of registered books to the command sender.
    default: false
  lore.command.respawn:
    description: Allows the player to set the flag for "respawn" on Lore books.
    default: false
  lore.command.sticky:
    description: Allows the player to set the flag for "sticky" on Lore books.
    default: false
  lore.join.obtain:
    description: Allows the player to obtain all books with the "join" flag set as true.
    default: false
  lore.respawn.obtain:
    description: Allows the player to obtain all books with the "respawn" flag set as true.
    default: false
  lore.sticky.bypass:
    description: Allows the player to not be bound by the sticky status of a book.
    default: false
